### PR TITLE
feat: 🚀 expose page prop in filename generator

### PR DESCRIPTION
**Pull request by jason-dark**
@dc7290 interested to hear your thoughts on this.

## Problem:
Image names matter for SEO. Googlebot uses image file names to extract information about subject matter and advises us to use filenames that are descriptive. Further information from Google [here](https://developers.google.com/search/docs/appearance/google-images#descriptive-titles-captions-filenames).

In one of my projects I load image files from a CDN that automatically generates hashed file names. These are non-descriptive and I want to automate renaming filenames for SEO as part of my build process.

I need to create unique filenames for each image on my site (as per the docs [here](https://next-export-optimize-images.vercel.app/docs/Configurations/basic-configuration#filenamegenerator)). Where things get difficult for me is that many pages of my website share the same images.

On the surface this wouldn't be a problem, except that for some reason Next.js tries to reload images from the old, incorrect source (prior to optimisation by this lib) on page change events. This is documented in this [open issue](https://github.com/dc7290/next-export-optimize-images/issues/385).

**I need a way to generate SEO friendly filenames that are truely unique for each image on my site.**

## Potential solution
Each image is rendered onto a page in my Nextjs site, and each page has a slug. If I can use the slug as a prop in my custom `filenameGenerator` then I can make a truely unique filename for each image that is human readable and SEO friendly.

This PR explores allowing a user to add a data-page="page-name" prop to their images. This value is then exposed as "page" in the custom filename generator and can be used for filename generation.

```
filenameGenerator?: (generatorProps: {
    path: string
    name: string
    width: number
    quality: number
    extension: string
    page: string
  }) => string
```

I'd be interested to hear your thoughts. Maybe there is a better way to achieve the same thing? Regarding the changes in this PR, I didn't find any tests that relate to this area of the code base. Maybe I was looking in the wrong place so if you can point me in the right direction I'd be happy to write tests.

### CODE REVIEW

**Comment by dc7290** [comment]
@jason-dark 

Very interesting topic!
It would be great if this library could solve this problem.

However, from reading the Google link, I don't think it is necessary to change the file name when the same image is used on multiple pages. I read that it has something to do with which page the image is used on, but not with putting it in the file name!
What are jason's thoughts on this point?

**Comment by jason-dark** [comment]
> @jason-dark
> 
> Very interesting topic! It would be great if this library could solve this problem.
> 
> However, from reading the Google link, I don't think it is necessary to change the file name when the same image is used on multiple pages. I read that it has something to do with which page the image is used on, but not with putting it in the file name! What are jason's thoughts on this point?

Hi @dc7290 

It might be helpful for me to explain the train of thought that lead to this PR:

- I want to use a custom `filenameGenerator` method to rename my image files.
- As these images are being loaded externally from a CDN they must each have a 100% unique filename.
- In my custom `filenameGenerator` method I have other logic (outside the scope of this lib) that resolves the CDN's hashed filenames to a SEO friendly slugified filename.
- On my Nextjs site, many of the same images are used on different pages.
- This means that I need some other variable to use when renaming an image file to ensure that its filename is unique.
- For SEO purposes, the slug of the page on which the image is rendered makes sense to use, hence this PR.

So while unnecessary to rename every single duplicate image for SEO reasons, it is necessary that every image has a unique filename for this lib to work.

I hope I've explained this clearly but please let me know if you would like more detail.

**Comment by dc7290** [comment]
@jason-dark 

> So while unnecessary to rename every single duplicate image for SEO reasons, it is necessary that every image has a unique filename for this lib to work.

I think this is somewhat incorrect!
Although there is a restriction against giving the same name to different images, I am aware that in this case we want to give different names to the same image.
Am I wrong?

**Comment by dc7290** [comment]
This one is temporarily closed!

**Pull request closed without merging**
